require_relative "./tests/registers_test"
require_relative "./tests/executor_test"
require_relative "./tests/display_test"
require_relative "./tests/commands_navigation_test"
require_relative "./tests/commands_register_manipulation_test"
